# Generated by Django 5.0.2 on 2025-03-24 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_update_tag_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
